name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_HUB_USERNAME/neural-style-transfer:v1 .
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
        docker push $DOCKER_HUB_USERNAME/neural-style-transfer:v1

    - name: Set AWS region
      run: echo "::set-env name=AWS_REGION::${{ secrets.AWS_DEFAULT_REGION }}"

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push Docker image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: v1
      run: |
        docker tag $DOCKER_HUB_USERNAME/neural-style-transfer:v1 $ECR_REGISTRY/$ECR_REPOSITORY:v1
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:v1
