name: Pull and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  pull-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ECR_BASE_PATH: public.ecr.aws/x7s1j2h0/style

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set AWS region
      run: echo "AWS_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> $GITHUB_ENV

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true
        registry-type: public


    - name: Build Docker image
      run: |
        docker build -t $DOCKER_HUB_USERNAME/neural-style-transfer:v1 .
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
        docker push $DOCKER_HUB_USERNAME/neural-style-transfer:v1

    - name: Pull Docker image from Docker Hub
      run: docker pull $DOCKER_HUB_USERNAME/neural-style-transfer:v1

    - name: Tag Docker image for ECR
      run: docker tag $DOCKER_HUB_USERNAME/neural-style-transfer:v1 ${{ steps.login-ecr.outputs.registry }}/$ECR_BASE_PATH/neural-style-transfer:v1

    - name: Push Docker image to ECR
      run: docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_BASE_PATH/neural-style-transfer:v1