name: CD Pipeline

on:
    workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull sid6601/neural-style-transfer:latest
    - name: Delete Old docker container
      run: sudo docker rm -f neural-style-transfer-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8000:8000 --name neural-style-transfer-container sid6601/neural-style-transfer
