name: Docker CI/CD Pipeline

on:
    workflow_dispatch:

jobs:

 build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
                
      - name: DockerHub login
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
                  
      - name: Pull Docker image from Docker Hub
        run: docker pull sid6601/image-style-fusion:latest

      - name: 