name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:

  deploy:
    name: Deploy to Lambda
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Replace with your desired AWS region

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Deploy to AWS Lambda
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: neural-style-transfer  # Replace with your ECR repository name
        IMAGE_TAG: v1  # Replace with your image tag
        FUNCTION_NAME: stylize-image-lambda  # Replace with your desired Lambda function name
      run: |
        # Create or update the Lambda function with the ECR image
        aws lambda update-function-code --function-name $FUNCTION_NAME \
          --image-uri ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
        
        # Configure environment variables for the Lambda function
        aws lambda update-function-configuration --function-name $FUNCTION_NAME \
        --environment "Variables={AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }},AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }},AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }},MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }},MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }},MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }},MODEL_URI=${{ secrets.MODEL_URI }}}"