name: Deploy to AWS Lambda

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  LAMBDA_FUNCTION_NAME: lambda-neural-style-transfer

jobs:

  deploy:
    name: Deploy to Lambda
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get image tag
      id: get_image_tag
      run: echo "::set-output name=image_tag::$(cat version.txt)"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Deploy or Create Lambda Function
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: neural-style-transfer
        IMAGE_TAG: ${{ steps.get_image_tag.outputs.image_tag }}
      run: |
        # Check if the Lambda function already exists
        FUNCTION_EXISTS=$(aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }} || echo "")

        if [ -z "$FUNCTION_EXISTS" ]; then
          # Create a new Lambda function
          aws lambda create-function \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --package-type Image \
            --code ImageUri=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --role arn:aws:iam::873393246907:role/lambda-role
        else
          # Update the existing Lambda function
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        fi