name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:

  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: sid6601/neural-style-transfer:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}


# sudo docker run -d \
# -p 8000:8000 \
# -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
# -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
# -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
# sid6601/neural-style-transfer