name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:

  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: DockerHub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: sid6601/neural-style-transfer:latest
        
