name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:

  build:
    name: Continuos Integration
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: DockerHub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: sid6601/image-style-fusion:latest

  deploy:
      name: Continuos Deployment
      needs: build
      runs-on: self-hosted
      steps:
        - name: Deploy to EC2 instance
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_PRIVATE_KEY }}
            script: |
              sudo docker pull sid6601/image-style-fusion:latest
              sudo docker rm -f image-style-fusion || true
              sudo docker run -d \
               -p 80:80 \
               -e AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} \
               -e AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} \
               -e AWS_DEFAULT_REGION=${{secrets.AWS_DEFAULT_REGION}} \
               --name image-style-fusion sid6601/image-style-fusion:latest
        
